app/todolist/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField, BooleanField
from wtforms import ValidationError
from wtforms.validators import DataRequired
from ..models import Category

class AddEventForm(FlaskForm):
    title = StringField('Event', validators = [DataRequired()])
    category = SelectField('Category',coerce = int)
    submit = SubmitField('Add')

    def __init__(self, *args, **kwargs):
        super(AddEventForm, self).__init__(*args, **kwargs)
        self.category.choices = [(category.id, category.name)
                                for category in Category.query.order_by(Category.name).all()]
class AddCategoryForm(FlaskForm):
    name = StringField('Category', validators = [DataRequired()])
    submit = SubmitField('Add')

    def validate_name(self, field):
        if Category.query.filter_by(name = field.data).first():
            raise ValidationError('The category you want to add already exit!')

class EditEventForm(FlaskForm):
    title = StringField('Event', validators = [DataRequired()])
    category = SelectField('Category', coerce=int)
    completion = BooleanField('Done')
    submit = SubmitField('Modified')

    def __init__(self, *args, **kwargs):
        super(EditEventForm, self).__init__(*args, **kwargs)
        self.category.choices = [(category.id, category.name)
                                for category in Category.query.order_by(Category.name).all()]

app/todolist/__init__.py
from flask import Blueprint

todolist = Blueprint('todolist', __name__)

from . import views

app/todolist/views.py
from flask import render_template, flash, redirect, url_for
from flask_login import login_required,current_user
from .forms import AddEventForm, AddCategoryForm, EditEventForm
from ..models import Event,Category
from . import todolist
from .. import db
import logging

@todolist.route('/show')
@login_required
def show():
    events = Event.query.filter_by(sponsor_id = current_user.id).all()
    # debug use
    #for event in events:
    #    print("event id={eventid}".format(eventid=event.id))
    if events is None:
        flash('You have noththing in todolist!')
    return render_template('todolist/show.html', events = events)

@todolist.route('/add-event',methods = ['GET', 'POST'])
@login_required
def add_event():
    form = AddEventForm()
    if form.validate_on_submit():
        event = Event(title = form.title.data,
                        category = Category.query.get(form.category.data),
                        sponsor = current_user._get_current_object())
        db.session.add(event)
        flash('Add event sucessfully!')
        return redirect(url_for('todolist.show'))
    return render_template('todolist/add_event.html', form = form)

@todolist.route('/add-category', methods= ['GET', 'POST'])
@login_required
def add_category():
    form = AddCategoryForm()
    if form.validate_on_submit():
        category = Category(name = form.name.data)
        db.session.add(category)
        flash('Add category successfully')
        return redirect(url_for('todolist.show'))
    return render_template('todo/add_category.html', form=form)

@todolist.route('/edit-event/<int:id>', methods = ['GET', 'POST'])
@login_required
def edit_event(id):
    event = Event.query.get_or_404(id)
    form = EditEventForm()
    if form.validate_on_submit():
        event.title = form.title.data
        event.category = Category.query.get(form.category.data)
        event.completion = form.completion.data
        db.session.add(event)
        flash('Event has been updated!')
        return redirect(url_for('.show'))
    form.title.data = event.title
    form.category.data = event.category_id
    form.completion.data = event.completion
    return render_template('todolist/edit_event.html',form=form)

@todolist.route('/delete-event/<int:id>', methods = ['GET', 'POST'])
@login_required
def delete_event(id):
    event = Event.query.get_or_404(id)
    db.session.delete(event)
    db.session.commit()
    return redirect(url_for('.show'))

@todolist.route('/finish/<int:id>')
@login_required
def finish(id):
    event = Event.query.get_or_404(id)
    if event:
        event.completion = True
        db.session.add(event)
        db.session.commit()
        return redirect(url_for('.show'))

app/templates/todolist/add_event.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Flasky - Add todo list event{% endblock %}
{% block page_content %}
<div class="page-header">
    <h1>Add todo list event</h1>
</div>
<div>
   {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/todolist/edit_event.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Flasky - Add todo list event{% endblock %}
{% block page_content %}
<div class="page-header">
    <h1>Edit todo list event</h1>
</div>
<div>
   {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/todolist/show.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Show todolist{% endblock %}
{% block page_content %}
<div class="page-header">
	<h1>Show todolist</h1>
</div>
<div>
<table class="table">
	<caption>我的待办事项</caption>
   <thead>
      <tr>
         <th>id</th>
         <th>标题</th>
         <th>是否完成</th>
         <th>创建时间</th>
      </tr>
   </thead>
   <tbody>
   {% for event in events %}
      <tr {% if event.completion %} class="success" {% endif %}>
         <td>{{ event.id }}</td>
         <td>{{ event.title}} </td>
         <td> {% if event.completion %}已完成{% else %}待完成{%endif%}</td>
         <td>{{ moment(event.create_time).fromNow() }}</td>
         <td>{% if event.completion %} <button type="button" class="btn btn-success">Done in time</button>{% endif %}
         </td>
         <td>
            <a href="{{ url_for('todolist.edit_event', id=event.id) }}"><button type="button" class="btn btn-info">编辑事件</button></a>
            <a href="{{ url_for('todolist.delete_event', id=event.id) }}"><button type="button" class="btn btn-danger">删除事件</button></a>
         </td>
      </tr>
   {% endfor %}
   </tbody>
</table>
<a href="{{ url_for('todolist.add_event') }}"><button type="button" class="btn btn-primary">添加事件</button></a>
</div>
{% endblock %}